package io.lara.ledger.domain;

import java.util.Objects;
import java.util.regex.Pattern;

/**
 * The caller's own name for a transaction, and the key that makes posting idempotent.
 *
 * <p>Supplied by whoever asks for the posting, not generated by the ledger — that is the whole
 * point. A reference the ledger invented would be different on every retry and would identify
 * nothing. The caller derives it from something stable about the request, so a retry carries the
 * same reference and the ledger recognises it.
 *
 * <p>Distinct from {@link TransactionId}, which is the ledger's own identity for what it recorded.
 * One reference maps to exactly one id, forever.
 */
public record TransactionReference(String value) implements Comparable<TransactionReference> {

    private static final int MAX_LENGTH = 128;
    private static final Pattern FORMAT = Pattern.compile("[A-Za-z0-9][A-Za-z0-9._:-]*");

    public TransactionReference {
        Objects.requireNonNull(value, "transaction reference must not be null");
        if (value.isBlank()) {
            throw new IllegalArgumentException("transaction reference must not be blank");
        }
        if (value.length() > MAX_LENGTH) {
            throw new IllegalArgumentException(
                    "transaction reference must be at most " + MAX_LENGTH + " characters, was " + value.length());
        }
        if (!FORMAT.matcher(value).matches()) {
            throw new IllegalArgumentException(
                    "transaction reference must be alphanumerics with . _ : or -, was '" + value + "'");
        }
    }

    public static TransactionReference of(String value) {
        return new TransactionReference(value);
    }

    @Override
    public int compareTo(TransactionReference other) {
        return value.compareTo(other.value);
    }

    @Override
    public String toString() {
        return value;
    }
}
